services:
  redis:
    image: redis:7.4.1
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: unless-stopped
  streamer:
    image: streamer
    container_name: streamer
    build:
      context: streamer/
      dockerfile: Dockerfile
    env_file:
      - secrets.env
    restart: unless-stopped
    depends_on:
      - redis
  remotecontrol:
    image: remotecontrol
    container_name: remotecontrol
    build:
      context: remotecontrol/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - secrets.env
    restart: unless-stopped
    depends_on:
      - redis
volumes:
  redis-data: