services:
  redis:
    image: redis:7.4.1
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server --requirepass your_password_here
  # streamer:
  #   image: streamer
  #   container_name: streamer
  #   build:
  #     context: streamer/
  #     dockerfile: Dockerfile
  #   env_file:
  #     - streamer-secrets.env
  #   restart: unless-stopped
  #   depends_on:
  #     - redis
  remotecontrol:
    image: remotecontrol
    container_name: remotecontrol
    build:
      context: remotecontrol/
      dockerfile: Dockerfile
    env_file:
      - remotecontrol-secrets.env
    volumes:
      - remotecontrol-data:/data
    restart: unless-stopped
    depends_on:
      - redis
volumes:
  redis-data:
  remotecontrol-data: